packages:
  - '.'

allowBuilds:
  esbuild: true

overrides:
  '@nerima-games/mc-kernel': 0.2.18
  '@nerima-games/mc-render': 0.2.14
  '@nerima-games/mc-sim': 0.1.42
  '@nerima-games/mc-worldgen': 0.1.14
  '@nerima-games/mx-gameplay': 0.3.1
